//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 10:01:53 AM EST 
//


package com.padmacareer.weather;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="weatherdetails" type="{http://padmacareer.com/weather}weatherdetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "weatherdetails"
})
@XmlRootElement(name = "GetWeatherDetailsResponse")
public class GetWeatherDetailsResponse {

    @XmlElement(required = true)
    protected Weatherdetails weatherdetails;

    /**
     * Gets the value of the weatherdetails property.
     * 
     * @return
     *     possible object is
     *     {@link Weatherdetails }
     *     
     */
    public Weatherdetails getWeatherdetails() {
        return weatherdetails;
    }

    /**
     * Sets the value of the weatherdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weatherdetails }
     *     
     */
    public void setWeatherdetails(Weatherdetails value) {
        this.weatherdetails = value;
    }

}
